/**
 * Helper that rewrites a user's `schema.graphql` to PRE-inject the three
 * DataStore conflict-resolution metadata fields (`_version`, `_deleted`,
 * `_lastChangedAt`) onto every `@model` type.
 *
 * Why this exists: when a user chooses "Disable conflict detection" in
 * `amplify update api` (the DISABLE_CONFLICT arm of `updateApiInputWalkthrough`),
 * the GraphQL transformer stops emitting those three fields on every model
 * type and every Update…Input. Any frontend code still wired to DataStore
 * (which always sends `_version` in mutation inputs) breaks immediately with
 * a GraphQL validation error.
 *
 * By pre-declaring the fields as regular user fields on the model, they
 * survive the transformer regeneration and the frontend keeps compiling
 * and running (albeit without server-managed concurrency semantics — that
 * trade-off is documented in the migration checklist printed alongside).
 *
 * This module is intentionally pure: string in → {string, lists} out.
 * No filesystem, no logging, no prompts. That makes it trivially testable
 * and safe to call from the walkthrough.
 *
 * See the migration guide: https://github.com/aws-amplify/docs/pull/8578
 */
import {
  parse,
  print,
  visit,
  DocumentNode,
  ObjectTypeDefinitionNode,
  FieldDefinitionNode,
  DirectiveNode,
  Kind,
} from 'graphql';

/**
 * The three DataStore/conflict-resolution metadata field names, in the
 * canonical order AppSync emits them.
 */
export const SYNC_FIELD_NAMES = ['_version', '_deleted', '_lastChangedAt'] as const;

/**
 * Mapping of sync-field name → GraphQL scalar type name used by AppSync.
 * `_lastChangedAt` uses the AppSync built-in `AWSTimestamp` scalar (epoch millis).
 */
const SYNC_FIELD_TYPES: Record<(typeof SYNC_FIELD_NAMES)[number], string> = {
  _version: 'Int',
  _deleted: 'Boolean',
  _lastChangedAt: 'AWSTimestamp',
};

/**
 * Result of {@link injectSyncFields}.
 */
export interface InjectSyncFieldsResult {
  /** Rewritten schema text (printed back from the AST). */
  updated: string;
  /**
   * Names of object types annotated with `@model` that were modified
   * (at least one of the three fields was missing and has been added).
   * Models that already declared all three fields are NOT included.
   */
  modifiedModels: string[];
  /**
   * Names of object types whose fields declare `@manyToMany(relationName: "...")`.
   * The auto-synthesized join type (e.g. `CardLabel` for `Card@manyToMany Label`)
   * does NOT appear in `schema.graphql` — it's generated by the transformer.
   * We cannot inject fields into it from the user's schema; the caller should
   * print a warning and point the user at a separate DDB cleanup step.
   */
  manyToManyModels: string[];
}

/**
 * Pre-inject the DataStore sync metadata fields (`_version`, `_deleted`,
 * `_lastChangedAt`) into every `@model` in the given schema.
 *
 * Behaviour:
 *  - Idempotent: a model that already declares all three fields is left
 *    alone and is not listed in `modifiedModels`.
 *  - Partial: a model that declares some but not all three fields gets the
 *    missing ones added (the existing declarations are preserved verbatim).
 *  - Scope: only object types with an `@model` directive are considered.
 *    Non-`@model` types (e.g. enums, custom types) are not touched.
 *  - `@manyToMany` awareness: any model with a field that has the
 *    `@manyToMany` directive is added to `manyToManyModels`. The
 *    **synthesized** join type (not present in user schema) is NOT
 *    injected — the caller is expected to warn the user.
 *  - Directive preservation: existing field directives (`@auth`, `@hasMany`,
 *    `@belongsTo`, `@index`, …) on other fields are untouched.
 *
 * @param schemaText Raw contents of `amplify/backend/api/<name>/schema.graphql`.
 * @returns Object with the rewritten schema and the lists of affected types.
 */
export const injectSyncFields = (schemaText: string): InjectSyncFieldsResult => {
  const ast: DocumentNode = parse(schemaText, { noLocation: true });
  const modifiedModels: string[] = [];
  const manyToManyModels: string[] = [];

  const rewritten = visit(ast, {
    ObjectTypeDefinition: {
      leave(node: ObjectTypeDefinitionNode): ObjectTypeDefinitionNode | undefined {
        const isModel = (node.directives ?? []).some((d: DirectiveNode) => d.name.value === 'model');
        if (!isModel) return undefined;

        const existingFieldNames = new Set((node.fields ?? []).map((f) => f.name.value));
        const hasManyToMany = (node.fields ?? []).some((f) =>
          (f.directives ?? []).some((d) => d.name.value === 'manyToMany'),
        );
        if (hasManyToMany) {
          manyToManyModels.push(node.name.value);
        }

        const toAdd: FieldDefinitionNode[] = [];
        for (const fieldName of SYNC_FIELD_NAMES) {
          if (existingFieldNames.has(fieldName)) continue;
          toAdd.push({
            kind: Kind.FIELD_DEFINITION,
            name: { kind: Kind.NAME, value: fieldName },
            type: {
              kind: Kind.NAMED_TYPE,
              name: { kind: Kind.NAME, value: SYNC_FIELD_TYPES[fieldName] },
            },
            directives: [],
          });
        }

        if (toAdd.length === 0) {
          return undefined;
        }

        modifiedModels.push(node.name.value);
        return {
          ...node,
          fields: [...(node.fields ?? []), ...toAdd],
        };
      },
    },
  }) as DocumentNode;

  return {
    updated: print(rewritten),
    modifiedModels,
    manyToManyModels,
  };
};
